# Generated by Django 3.2.8 on 2021-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('serviceImage', models.ImageField(default='default.jpeg', upload_to='service')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceImage',
        ),
    ]
