# Generated by Django 3.2.8 on 2021-11-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fullName',
            field=models.CharField(default='John Doe', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceImage',
            field=models.ImageField(default='default.jpeg', upload_to='service'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profilePicture',
            field=models.ImageField(default='default.png', upload_to='appuser'),
        ),
    ]
