# Generated by Django 3.2.8 on 2021-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='userName',
            field=models.CharField(default='defaultname', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
