# Generated by Django 3.2.8 on 2021-10-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0002_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='userName',
        ),
    ]
