# Generated by Django 3.2.8 on 2021-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0003_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='serviceImage',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(default='default.jpeg', upload_to='category'),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceImage',
            field=models.ImageField(default='default.jpeg', upload_to='service'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ServiceCreed.category'),
        ),
    ]
