# Generated by Django 3.2.8 on 2021-10-30 08:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0004_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='mobileNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
