# Generated by Django 3.2.8 on 2021-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0005_auto_20211107_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscriptionPeriod',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
