# Generated by Django 3.2.8 on 2021-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0005_appuser_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
