# Generated by Django 3.2.8 on 2021-10-30 10:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCreed', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Successfull', 'Success'), ('Failed', 'Fail')], max_length=16)),
                ('paymentMethod', models.CharField(choices=[('Debit Card/Credit Card', 'Card'), ('Cash on Delivery', 'Cash')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='testfield',
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ServiceCreed.appuser')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_given_category', to='ServiceCreed.service')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('ServiceCreed.appuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCustomerOrders', to='ServiceCreed.customer')),
                ('paymentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetails', to='ServiceCreed.paymentdetails')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myServiceOrders', to='ServiceCreed.serviceprovider')),
            ],
        ),
    ]
